#%RAML 1.0 SecurityScheme
type: x-token-authorize
description: This will make sure you have authorisation token
describedBy:
  headers:
    Authorization: 
      type: string
  responses:
    401:
      description: 401-unauthorized